### ISSUE TITLE
Test Single Image

### ISSUE THREAD

**Issue by zhangrule9** [fraunhoferhhi/CuriouslyEffectiveIQE#1]
Hello, I need your help. How to test single image?

**Comment by soerenab** [comment]
Hi zhangrule9, Thanks for your interest. This code is not really meant to be deployed on images that we did not use in our paper. If you want to try out the model on your own image, you will have to adapt the code for feature extraction and the code from the jupyter notebook to evaluate a trained SVR on your extracted features. If you want to do this and need help, please let me know.

**Comment by zhangrule9** [comment]
Hello soerenab,thank you  for your reply.  I use codebooks=10000, max_blocks=10000,the test time is about 3s.
