### ISSUE TITLE
How to reproduce result about paper Fig 2?

### ISSUE THREAD

**Issue by zhangrule9** [fraunhoferhhi/CuriouslyEffectiveIQE#2]
![image](https://user-images.githubusercontent.com/87051541/127441574-8a9c9f53-0c19-4f73-8ea8-35815238323b.png)
Hello,as shown in Figure 2, the PCC changes with the feature number. What is the size of the codebook in the figure?

**Comment by soerenab** [comment]
Hi zhangrule9, thanks for your interest! All results in the paper were obtained with the same codebook models which have 10000 codes, which leads to 20000 features (due to the non-linearity, i.e., the vector of max() functions on page 2, left column). For figure 2 we selected the m = {50,100,200,...,3000} most important features from the full codebook model, where the importance is determined by the absolute value of the (linear) SVR coefficients which was trained using all 10000 codes (/20000 features). I hope this helps, otherwise let me know.

**Comment by zhangrule9** [comment]
Hello soerenab,Is it possible to reproduce the results of the paper with a small number of codebooks?For example, using 150 codebooks and max_blocks=150 to reproduce SRCC and PCC. Must I use 10000 codes?what do you think?

**Comment by soerenab** [comment]
A couple of thoughts on this: 
1) I have not played with the max_blocks parameter too much so I can't really tell. My intuition is that max_blocks=150 is too low to get very high correlations.
2) If you start with a codebook of 150 codes (=300 features), you probably won't reach very high correlations - even if you use all the features. If I look at Fig. 2, the 150 *most important* features (/out of all 20000 features) yield correlations of about 0.85.
3) About the double descent phenomenon: The trough occurs when the number of features matches (roughly) the number of samples of your training dataset. Therefore, to reproduce this effect, you will need more features than you have samples.

**Comment by zhangrule9** [comment]
m = {50,100,200,...,3000},what's mean m?How to understand it?

**Comment by soerenab** [comment]
For the detailed answer have a look at Sec. 4.2 ("How well do the best codes perform?") in the paper. In short: we initially construct a codebook of k=10000 codes (=20000 features). Out of these 20000 features, we select m = {50, 100, ...} features by their importance and repeat the training and evaluation of the SVR. That is, firstly we select m=50 features and repeat training and evaluation, then we select m=100 features and repeat training and evaluation, ..., finally we select m=3000 features and repeat training and evaluation. (m is chosen arbitrarily but covers the range where we see the double descent effect.)

(edited to make notation consistent with paper)

**Comment by zhangrule9** [comment]
I understand m={50,10,...}, it represents max_blocks parameters. Is my understanding correct?
![image](https://user-images.githubusercontent.com/87051541/128834622-f5317822-5187-4b50-ae6a-d74ec691271f.png)

**Comment by soerenab** [comment]
No, max_blocks != m. max_blocks represents the number of 7x7 patches that you extract from a single image. In our code (and for all results in the paper) this is set to max_blocks = 10000 (which is also the number used in the original CORNIA paper, if I remember correctly). m is another hyper-parameter that we just introduced and used to analyze our results. max_blocks corresponds to parameter l in section 2 ("Computational framework").

**Comment by zhangrule9** [comment]
In the open source that you provide, how to set parameters m?

**Comment by zhangrule9** [comment]
The logic for setting m  parameters is not found in the open source code.

**Comment by zhangrule9** [comment]
![image](https://user-images.githubusercontent.com/87051541/130021619-fbf80c48-3cde-4958-a83b-6354a7e6dbdb.png)
hello soerenab,Which value does the pcc represent?
![image](https://user-images.githubusercontent.com/87051541/130021787-4605c1de-8843-44c0-ba73-c4f2f7922372.png)

**Comment by soerenab** [comment]
The results in figure 2 represent average correlations across 10 random test splits, which include all available distortion types in the LIVE database (="full").

**Comment by zhangrule9** [comment]
I take the maximum 150 values based on the absolute value of the SVR coefficient.The model was retrained by taking 150 codebook values based on their subscripts.
![image](https://user-images.githubusercontent.com/87051541/130033596-7f055ad9-fe47-4aa1-9b21-ff2566118a57.png)Why can't the result shown in Figure 2 be reproduced?Am I doing the right thing?

**Comment by soerenab** [comment]
Here is some code to reproduce figures 1 and 2. Just paste it in a new cell at the end of the Experiment.ipynb notebook. You will have to run the training of the SVM on all 20000 features for all splits and all models first.

for fig 1:
````
plt.figure(figsize=(8,4))

for codebook in data.codebook.unique():
    # load svr model
    svr = load("./regression_models/svr_{}_0.joblib".format(codebook))
    # plot distribution of sorted absolute coefficients
    plt.plot(sorted(np.abs(svr.coef_).squeeze())[::-1], "--", label=codebook)

plt.legend(frameon=False)
plt.xlabel("feature index")
plt.ylabel("|SVR coef|")
plt.ylim([-0.0002, 0.005])
plt.xticks([0, 5000, 10000, 15000, 20000])
plt.yticks([0, 0.006])
plt.show()
````

for fig 2 (the one you are trying to reproduce):
````
# Define subset sizes
m_features = [10, 50, 100] + list(np.linspace(50, 1000, 20).astype(int)) + [1200, 1400, 1600, 1800, 2000, 2500, 3000]

# Allocate arrays to store results in later on
pcc_subsets_train = np.zeros([len(data.codebook.unique()), 10, len(m_features)])
pcc_subsets_val = np.zeros([len(data.codebook.unique()), 10, len(m_features)])

# Iterate over models
for codebookIdx, codebook in tqdm(enumerate(data.codebook.unique())):
    
    # Iterate over random splits (we use the same splits as before)
    for split in tqdm(range(10), leave=False):

        # Select corresponding data
        idcs = (data.codebook == codebook) & \
               (data.dataset == "liveiqa")

        # Split data into train and val (there are predefined splits)
        data_train = pd.DataFrame(columns=data.columns.tolist())
        data_train = data_train.append(data.loc[idcs & (~data.refname.isin(val_names[split]))])

        data_val = pd.DataFrame(columns=data.columns.tolist())
        data_val = data_val.append(data.loc[idcs & (data.refname.isin(val_names[split]))])

        # Load svr model that uses all 10000 codes (=20000 features)
        svr10000 = load("./regression_models/svr_{}_0.joblib".format(codebook))

        # Iterate over features subset sizes
        for mIdx, m in tqdm(enumerate(m_features), leave=False):

            # Select m features based on absolute value of coefficients of the full svr
            selected_feature_idcs = np.argsort(np.abs(svr10000.coef_).squeeze())[::-1][0:m]

            # Get features
            betas_train = np.vstack(data_train.beta.values)[:, selected_feature_idcs]
            betas_val = np.vstack(data_val.beta.values)[:, selected_feature_idcs]

            # On training data, find parameters to scale features to the range [-1, 1]
            scaler = MinMaxScaler(feature_range=[-1,1])
            scaler.fit(betas_train)

            # Apply parameters to train and test data
            betas_train = scaler.transform(betas_train)
            betas_val = scaler.transform(betas_val)

            # Fit support vector machine
            svr = svm.NuSVR(kernel='linear', C=1.0, nu=0.5, cache_size=1000)
            svr.fit(betas_train, data_train.q_norm)

            # Save results on training set
            pcc_subsets_train[codebookIdx, split, mIdx] = pearsonr(svr.predict(betas_train), data_train.q_norm)[0]

            # Save results on test set
            pcc_subsets_val[codebookIdx, split, mIdx] = pearsonr(svr.predict(betas_val), data_val.q_norm)[0]
    
    # plot results for this codebook model, averaged across random splits
    plt.plot(m_features, pcc_subsets_val[codebookIdx].mean(axis=0).squeeze(), "o--", markerfacecolor="white", label=codebook)    
    
plt.ylim([0.5, 1])
plt.xlabel("number of features")
plt.ylabel("PCC")
plt.legend(frameon=False)
plt.show()
````

I try to update the code in the repo soon but I hope this works for you in the meantime. I can reproduce the figures from the paper fairly well with this code.

(Edit: fixed path for loading svr models.)
