### ISSUE TITLE
Missing trailing s in docs of format_datasets.py

### ISSUE THREAD

**Issue by otaviojacobi** [fraunhoferhhi/CuriouslyEffectiveIQE#4]
Hi, 

When reproducing your code I noticed that the ```format_datasets.py``` documentation has a few examples of how to run the script. However, these example currently don't work due to a typo where the missing trailing ```s```. I have created a pr #3 with the fix.

Thanks and Best regards,
Otávio

**Comment by soerenab** [comment]
Thanks for pointing that out!
